WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=34171): Read timed out. (read timeout=120)")': /session/ba7b5998d4d1efad4fdc7adc90c89e82/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=34171): Read timed out. (read timeout=120)")': /session/ba7b5998d4d1efad4fdc7adc90c89e82/screenshot