{"uid":"9bb06aa37f97e417","name":"Авторизация пользователя с валидными данными по логину","fullName":"tests.test_authorization.TestAuthUser#test_auth_valid_user","historyId":"54e96611544e721e3fbef570988f687a","time":{"start":1739309987418,"stop":1739310021669,"duration":34251},"description":"При проверке используются валидные данные пользователя Aleska","descriptionHtml":"<p>При проверке используются валидные данные пользователя Aleska</p>\n","status":"failed","statusMessage":"AssertionError: Ожидалась страница https://staging.round.zone/rubric, но открылась https://staging.round.zone/. Страница не загрузилась за 10 секунд.","statusTrace":"self = <base.base_assertion.Assertion object at 0x7f2e18b2eea0>\npage_url = 'https://staging.round.zone/rubric', timeout = 10\n\n    def page_is_opened(self, page_url, timeout=10):\n        \"\"\"\n        Функция проверки, что запрашиваемая страница открыта\n    \n        :param page_url:\n            url страницы\n        :param timeout:\n            время ожидания в секундах\n        \"\"\"\n        try:\n            self.element_is_not_visible(AllPageLocators.locators['Спиннер загрузки'])\n>           self.wait.until(EC.url_to_be(page_url), timeout)\n\nbase/base_assertion.py:60: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"c58d42f8f79dbf6cab7765f0175e5f83\")>\nmethod = <function url_to_be.<locals>._predicate at 0x7f2e188d05e0>\nmessage = 10\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            if time.monotonic() > end_time:\n                break\n            time.sleep(self._poll)\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: 10\n\n../local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_authorization.TestAuthUser object at 0x7f2e19461d90>\nelements = {'Банк ачивок': {'Блок ачивок': ('xpath', '//div[contains(@class,\"user-achievement-by-interests_container\")]'), 'Модал...'carrot-messenger-frame'), 'Чат кэррот': ('xpath', '//div[contains(@class,\"carrot-messenger-frame-container\")]')}, ...}\n\n    @allure.title('Авторизация пользователя с валидными данными по логину')\n    @allure.description('При проверке используются валидные данные пользователя Aleska')\n    @allure.severity('Critical')\n    @pytest.mark.regression\n    def test_auth_valid_user(self, elements):\n        with allure.step('Открыть страницу логина'):\n            self.login_page.open()\n            element = elements['Страница логина']\n    \n        with allure.step('В поле логина вводим валидный никнейм'):\n            self.login_page.field_send_keys(element['Поле логин'], self.User.LOGIN)\n    \n        with allure.step('В поле пароля вводим валидный пароль'):\n            self.login_page.field_send_keys(element['Поле пароль'], self.User.PASSWORD)\n    \n        with allure.step('Нажать кнопку \"Войти\"'):\n            self.login_page.do_click(element['Кнопка войти'])\n    \n        with allure.step('Проверяем, что открыта страница рубрики'):\n>           self.assertion.page_is_opened(self.rubric_page.PAGE_URL)\n\ntests/test_authorization.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <base.base_assertion.Assertion object at 0x7f2e18b2eea0>\npage_url = 'https://staging.round.zone/rubric', timeout = 10\n\n    def page_is_opened(self, page_url, timeout=10):\n        \"\"\"\n        Функция проверки, что запрашиваемая страница открыта\n    \n        :param page_url:\n            url страницы\n        :param timeout:\n            время ожидания в секундах\n        \"\"\"\n        try:\n            self.element_is_not_visible(AllPageLocators.locators['Спиннер загрузки'])\n            self.wait.until(EC.url_to_be(page_url), timeout)\n        except TimeoutException:\n            current_url = self.driver.current_url\n>           raise AssertionError(f'Ожидалась страница {page_url}, но открылась {current_url}. '\n                                 f'Страница не загрузилась за {timeout} секунд.')\nE           AssertionError: Ожидалась страница https://staging.round.zone/rubric, но открылась https://staging.round.zone/. Страница не загрузилась за 10 секунд.\n\nbase/base_assertion.py:63: AssertionError","flaky":false,"newFailed":true,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1739309473698,"stop":1739309473699,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1739309986993,"stop":1739309987417,"duration":424},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Инициализация локаторов","time":{"start":1739309987417,"stop":1739309987417,"duration":0},"status":"passed","steps":[{"name":"Инициализация локаторов","time":{"start":1739309987417,"stop":1739309987417,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"request","value":"<SubRequest 'elements' for <Function test_auth_valid_user>>"}],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":1,"hasContent":true,"attachmentStep":false},{"name":"setup","time":{"start":1739309987417,"stop":1739309987417,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"При проверке используются валидные данные пользователя Aleska","status":"failed","statusMessage":"AssertionError: Ожидалась страница https://staging.round.zone/rubric, но открылась https://staging.round.zone/. Страница не загрузилась за 10 секунд.","statusTrace":"self = <base.base_assertion.Assertion object at 0x7f2e18b2eea0>\npage_url = 'https://staging.round.zone/rubric', timeout = 10\n\n    def page_is_opened(self, page_url, timeout=10):\n        \"\"\"\n        Функция проверки, что запрашиваемая страница открыта\n    \n        :param page_url:\n            url страницы\n        :param timeout:\n            время ожидания в секундах\n        \"\"\"\n        try:\n            self.element_is_not_visible(AllPageLocators.locators['Спиннер загрузки'])\n>           self.wait.until(EC.url_to_be(page_url), timeout)\n\nbase/base_assertion.py:60: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"c58d42f8f79dbf6cab7765f0175e5f83\")>\nmethod = <function url_to_be.<locals>._predicate at 0x7f2e188d05e0>\nmessage = 10\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            if time.monotonic() > end_time:\n                break\n            time.sleep(self._poll)\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: 10\n\n../local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_authorization.TestAuthUser object at 0x7f2e19461d90>\nelements = {'Банк ачивок': {'Блок ачивок': ('xpath', '//div[contains(@class,\"user-achievement-by-interests_container\")]'), 'Модал...'carrot-messenger-frame'), 'Чат кэррот': ('xpath', '//div[contains(@class,\"carrot-messenger-frame-container\")]')}, ...}\n\n    @allure.title('Авторизация пользователя с валидными данными по логину')\n    @allure.description('При проверке используются валидные данные пользователя Aleska')\n    @allure.severity('Critical')\n    @pytest.mark.regression\n    def test_auth_valid_user(self, elements):\n        with allure.step('Открыть страницу логина'):\n            self.login_page.open()\n            element = elements['Страница логина']\n    \n        with allure.step('В поле логина вводим валидный никнейм'):\n            self.login_page.field_send_keys(element['Поле логин'], self.User.LOGIN)\n    \n        with allure.step('В поле пароля вводим валидный пароль'):\n            self.login_page.field_send_keys(element['Поле пароль'], self.User.PASSWORD)\n    \n        with allure.step('Нажать кнопку \"Войти\"'):\n            self.login_page.do_click(element['Кнопка войти'])\n    \n        with allure.step('Проверяем, что открыта страница рубрики'):\n>           self.assertion.page_is_opened(self.rubric_page.PAGE_URL)\n\ntests/test_authorization.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <base.base_assertion.Assertion object at 0x7f2e18b2eea0>\npage_url = 'https://staging.round.zone/rubric', timeout = 10\n\n    def page_is_opened(self, page_url, timeout=10):\n        \"\"\"\n        Функция проверки, что запрашиваемая страница открыта\n    \n        :param page_url:\n            url страницы\n        :param timeout:\n            время ожидания в секундах\n        \"\"\"\n        try:\n            self.element_is_not_visible(AllPageLocators.locators['Спиннер загрузки'])\n            self.wait.until(EC.url_to_be(page_url), timeout)\n        except TimeoutException:\n            current_url = self.driver.current_url\n>           raise AssertionError(f'Ожидалась страница {page_url}, но открылась {current_url}. '\n                                 f'Страница не загрузилась за {timeout} секунд.')\nE           AssertionError: Ожидалась страница https://staging.round.zone/rubric, но открылась https://staging.round.zone/. Страница не загрузилась за 10 секунд.\n\nbase/base_assertion.py:63: AssertionError","steps":[{"name":"Открыть страницу логина","time":{"start":1739309987418,"stop":1739309989925,"duration":2507},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false},{"name":"В поле логина вводим валидный никнейм","time":{"start":1739309989925,"stop":1739309991503,"duration":1578},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false},{"name":"В поле пароля вводим валидный пароль","time":{"start":1739309991503,"stop":1739309991553,"duration":50},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Нажать кнопку \"Войти\"","time":{"start":1739309991553,"stop":1739309991596,"duration":43},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Проверяем, что открыта страница рубрики","time":{"start":1739309991596,"stop":1739310021669,"duration":30073},"status":"failed","statusMessage":"AssertionError: Ожидалась страница https://staging.round.zone/rubric, но открылась https://staging.round.zone/. Страница не загрузилась за 10 секунд.\n","statusTrace":"  File \"/usr/workspace/tests/test_authorization.py\", line 32, in test_auth_valid_user\n    self.assertion.page_is_opened(self.rubric_page.PAGE_URL)\n  File \"/usr/workspace/base/base_assertion.py\", line 63, in page_is_opened\n    raise AssertionError(f'Ожидалась страница {page_url}, но открылась {current_url}. '\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"stepsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"stepsCount":5,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"driver::0","time":{"start":1739310021680,"stop":1739310021893,"duration":213},"status":"passed","steps":[],"attachments":[{"uid":"34b2c230b6fedd4b","name":"page_source","source":"34b2c230b6fedd4b.html","type":"text/html","size":31670},{"uid":"23db229d621b9fa5","name":"screenshot","source":"23db229d621b9fa5.png","type":"image/png","size":60721},{"uid":"ebe7d59c4401122b","name":"browser_logs","source":"ebe7d59c4401122b.txt","type":"text/plain","size":6709}],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":3,"stepsCount":0,"hasContent":true,"attachmentStep":false}],"labels":[{"name":"feature","value":"Авторизация пользователя"},{"name":"severity","value":"Critical"},{"name":"tag","value":"regression"},{"name":"tag","value":"authorization"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_authorization"},{"name":"subSuite","value":"TestAuthUser"},{"name":"host","value":"e56e35b24cd4"},{"name":"thread","value":"1-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_authorization"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":1,"broken":1,"skipped":0,"passed":61,"unknown":0,"total":63},"items":[{"uid":"644f6c9d76c5e426","status":"passed","time":{"start":1738951541471,"stop":1738951547592,"duration":6121}},{"uid":"13ced84da4c56dc2","status":"passed","time":{"start":1738874856382,"stop":1738874861330,"duration":4948}},{"uid":"7cc6061a2d68dad6","status":"passed","time":{"start":1738871498355,"stop":1738871504915,"duration":6560}},{"uid":"243d6487f56fe8b9","status":"passed","time":{"start":1738864872206,"stop":1738864877495,"duration":5289}},{"uid":"6b6d437ac44281be","status":"passed","time":{"start":1738268520294,"stop":1738268526637,"duration":6343}},{"uid":"366f0ecb06069be9","status":"passed","time":{"start":1738098959979,"stop":1738098966372,"duration":6393}},{"uid":"9ee6dfae2be796f6","status":"passed","time":{"start":1738004968922,"stop":1738004975007,"duration":6085}},{"uid":"5b5aca3a9b25a834","status":"passed","time":{"start":1738002305171,"stop":1738002310429,"duration":5258}},{"uid":"a7c4f794cfb109b8","status":"passed","time":{"start":1737927425824,"stop":1737927455070,"duration":29246}},{"uid":"dd894c5463c5ae26","status":"passed","time":{"start":1737842570730,"stop":1737842578604,"duration":7874}},{"uid":"c7dd0ac20ace28a4","status":"passed","time":{"start":1737831873807,"stop":1737831879117,"duration":5310}},{"uid":"552ce42ab2396a23","status":"passed","time":{"start":1737799206655,"stop":1737799211768,"duration":5113}},{"uid":"d72aa6552650e80","status":"passed","time":{"start":1737757481456,"stop":1737757486710,"duration":5254}},{"uid":"995d3f9b0f1f6e5e","status":"passed","time":{"start":1737744440548,"stop":1737744445712,"duration":5164}},{"uid":"32c39052132a6a4f","status":"passed","time":{"start":1737652214937,"stop":1737652222257,"duration":7320}},{"uid":"fe3ac8e7ce39fd63","status":"passed","time":{"start":1737569837221,"stop":1737569843141,"duration":5920}},{"uid":"99643bc97ecf3c4d","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)","time":{"start":1737568959649,"stop":1737568959649,"duration":0}},{"uid":"ac82ea52725c2e75","status":"passed","time":{"start":1734034253454,"stop":1734034258982,"duration":5528}},{"uid":"71a40f136216c90e","status":"passed","time":{"start":1733936899925,"stop":1733936905568,"duration":5643}},{"uid":"28b6fa6b06967f8a","status":"passed","time":{"start":1733865386586,"stop":1733865392081,"duration":5495}}]},"tags":["authorization","regression"]},"source":"9bb06aa37f97e417.json","parameterValues":[]}