{"uid":"e0eaddd146eee04a","name":"Проверка возможности подписаться","fullName":"tests.test_profile.TestProfile#test_opportunities_to_subscribe","historyId":"8837be03da4b857171429e7b0d59755b","time":{"start":1738865312078,"stop":1738865312078,"duration":0},"description":"После проверки, отписываемся от пользователя для приведения в исходное состояние","descriptionHtml":"<p>После проверки, отписываемся от пользователя для приведения в исходное состояние</p>\n","status":"broken","statusMessage":"KeyError: 'access_token'","statusTrace":"request = <SubRequest 'login_to_app' for <Function test_opportunities_to_subscribe>>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f38b1ae0573526af0b201d5a17ff8030\")>\n\n    @pytest.fixture(scope='function')\n    @allure.title('Авторизация пользователя в системе')\n    @allure.step('Авторизация пользователя в системе')\n    def login_to_app(request, driver):\n        \"\"\" Фикстура Логина в систему \"\"\"\n        login_page = ApiAuthorization(driver)\n>       login_page.user(User.LOGIN, User.PASSWORD)\n\nconftest.py:53: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <model.api.authorization.ApiAuthorization object at 0x7f0ee2dff980>\nusername = 'Aleska', password = 'qwe123'\n\n    def user(self, username: str, password: str) -> None:\n        \"\"\"\n        Метод авторизации пользователя по средствам API.\n    \n        :param username: Логин пользователя\n        :param password: Пароль пользователя\n        \"\"\"\n        headers = {\n            'X-Client-Id': 'round',\n            'X-Client-Type': 'web',\n            'X-Language': 'ru'\n        }\n        data = {\n            'client_id': 'Krujok.Online.Mobile',\n            'grant_type': 'password',\n            'username': username,\n            'password': password\n        }\n    \n        response = requests.post(url=Api.TOKEN, headers=headers, data=data)\n>       access_token = response.json()[\"access_token\"]\nE       KeyError: 'access_token'\n\nmodel/api/authorization.py:30: KeyError","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1738864340794,"stop":1738864340795,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1738865312078,"stop":1738865312493,"duration":415},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Авторизация пользователя в системе","time":{"start":1738865312494,"stop":1738865312987,"duration":493},"status":"broken","statusMessage":"KeyError: 'access_token'\n","statusTrace":"  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/usr/workspace/conftest.py\", line 53, in login_to_app\n    login_page.user(User.LOGIN, User.PASSWORD)\n  File \"/usr/workspace/model/api/authorization.py\", line 30, in user\n    access_token = response.json()[\"access_token\"]\n                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n","steps":[{"name":"Авторизация пользователя в системе","time":{"start":1738865312494,"stop":1738865312987,"duration":493},"status":"broken","statusMessage":"KeyError: 'access_token'\n","statusTrace":"  File \"/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/usr/workspace/conftest.py\", line 53, in login_to_app\n    login_page.user(User.LOGIN, User.PASSWORD)\n  File \"/usr/workspace/model/api/authorization.py\", line 30, in user\n    access_token = response.json()[\"access_token\"]\n                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[{"name":"request","value":"<SubRequest 'login_to_app' for <Function test_opportunities_to_subscribe>>"},{"name":"driver","value":"<selenium.webdriver.chrome.webdriver.WebDriver (session=\"f38b1ae0573526af0b201d5a17ff8030\")>"}],"shouldDisplayMessage":true,"attachmentsCount":0,"stepsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":1,"hasContent":true,"attachmentStep":false},{"name":"Инициализация локаторов","time":{"start":1738865312494,"stop":1738865312494,"duration":0},"status":"passed","steps":[{"name":"Инициализация локаторов","time":{"start":1738865312494,"stop":1738865312494,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"request","value":"<SubRequest 'elements' for <Function test_opportunities_to_subscribe>>"}],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":1,"hasContent":true,"attachmentStep":false},{"name":"setup","time":{"start":1738865312494,"stop":1738865312494,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"driver::0","time":{"start":1738865312994,"stop":1738865313177,"duration":183},"status":"passed","steps":[],"attachments":[{"uid":"4d71881859ab5a16","name":"page_source","source":"4d71881859ab5a16.html","type":"text/html","size":39},{"uid":"2b6ed96c0a38c318","name":"screenshot","source":"2b6ed96c0a38c318.png","type":"image/png","size":10592},{"uid":"4d72b5a2d60b618d","name":"browser_logs","source":"4d72b5a2d60b618d.txt","type":"text/plain","size":0}],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":3,"stepsCount":0,"hasContent":true,"attachmentStep":false}],"labels":[{"name":"feature","value":"Профиль пользователя"},{"name":"severity","value":"Critical"},{"name":"tag","value":"regression"},{"name":"tag","value":"profile"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_profile"},{"name":"subSuite","value":"TestProfile"},{"name":"host","value":"6af98febc332"},{"name":"thread","value":"1-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_profile"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":12,"broken":8,"skipped":0,"passed":19,"unknown":0,"total":39},"items":[{"uid":"83a1d83d3050f111","status":"failed","statusDetails":"AssertionError: Ожидался текст: '2', отображается текст: '1'","time":{"start":1738269328664,"stop":1738269334101,"duration":5437}},{"uid":"393fc5fb81706fa9","status":"failed","statusDetails":"AssertionError: Ожидался текст: '2', отображается текст: '1'","time":{"start":1738099800199,"stop":1738099808600,"duration":8401}},{"uid":"1a1c26198a21bd47","status":"failed","statusDetails":"AssertionError: Ожидался текст: '2', отображается текст: '1'","time":{"start":1738005655996,"stop":1738005661415,"duration":5419}},{"uid":"bb37ea67897004f9","status":"failed","statusDetails":"AssertionError: Ожидался текст: '2', отображается текст: '1'","time":{"start":1738002934635,"stop":1738002940052,"duration":5417}},{"uid":"41baf7984698b959","status":"broken","statusDetails":"selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome=132.0.6834.83); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception","time":{"start":1737932558826,"stop":1737932558826,"duration":0}},{"uid":"c64e506b5b3bf6fd","status":"failed","statusDetails":"AssertionError: Ожидался текст: '2', отображается текст: '1'","time":{"start":1737843315212,"stop":1737843322169,"duration":6957}},{"uid":"44c71df5ac64d686","status":"failed","statusDetails":"AssertionError: Ожидался текст: '2', отображается текст: '1'","time":{"start":1737832501768,"stop":1737832508742,"duration":6974}},{"uid":"ce1adce00b0b9cd","status":"failed","statusDetails":"AssertionError: Ожидался текст: '2', отображается текст: '1'","time":{"start":1737799865822,"stop":1737799872800,"duration":6978}},{"uid":"c3ba876983d362af","status":"failed","statusDetails":"AssertionError: Ожидался текст: '2', отображается текст: '1'","time":{"start":1737758099860,"stop":1737758106847,"duration":6987}},{"uid":"681cab165fc587d7","status":"failed","statusDetails":"AssertionError: Ожидался текст: '2', отображается текст: '1'","time":{"start":1737745092073,"stop":1737745099043,"duration":6970}},{"uid":"6412b3cf34021890","status":"failed","statusDetails":"AssertionError: Ожидался текст: '2', отображается текст: '1'","time":{"start":1737652984595,"stop":1737652992082,"duration":7487}},{"uid":"6f9148b3096adb32","status":"failed","statusDetails":"AssertionError: Ожидался текст: '2', отображается текст: '1'","time":{"start":1737570658842,"stop":1737570666395,"duration":7553}},{"uid":"1a48054d733defb1","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)","time":{"start":1737568968602,"stop":1737568968602,"duration":0}},{"uid":"5f1fbecb0e9504cc","status":"failed","statusDetails":"AssertionError: Ожидался текст: '8', отображается текст: '7'","time":{"start":1734034910933,"stop":1734034917944,"duration":7011}},{"uid":"6c8e11255c7cf244","status":"passed","time":{"start":1733937646919,"stop":1733937656990,"duration":10071}},{"uid":"89eff593bf137b2d","status":"passed","time":{"start":1733866218449,"stop":1733866227027,"duration":8578}},{"uid":"74fe727b4307f185","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: Не найден элемент с локатором ('xpath', '//button[@data-testing=\"after_register_dialog__btn_choose_later\"]')","time":{"start":1733860651908,"stop":1733860651908,"duration":0}},{"uid":"4b88ab3497331841","status":"passed","time":{"start":1733857242645,"stop":1733857251217,"duration":8572}},{"uid":"58160b9da1f32e6d","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: Не найден элемент с локатором ('xpath', '//button[@data-testing=\"after_register_dialog__btn_choose_later\"]')","time":{"start":1733772122579,"stop":1733772122579,"duration":0}},{"uid":"cd775cec30479bbe","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: Не найден элемент с локатором ('xpath', '//button[@data-testing=\"after_register_dialog__btn_choose_later\"]')","time":{"start":1733766597191,"stop":1733766597191,"duration":0}}]},"tags":["regression","profile"]},"source":"e0eaddd146eee04a.json","parameterValues":[]}